### ISSUE TITLE
Doesn't work (reddit?)

### ISSUE THREAD

**Issue by peter-kehl** [igorlogius/indicate-if-link-is-bookmarked#2]
Hi Igor,

Thank you for creating this add-on.

On current Firefox 100 on current Manjaro x64 Linux, I have https://www.uscis.gov/citizenship-resource-center/learn-about-citizenship/naturalization-eligibility bookmarked (as indicated by the green icon right of the address bar, and I confirmed by a search in my FF bookmarks):
![image](https://user-images.githubusercontent.com/4270240/167998500-1ab5efa3-53cb-4ca6-8820-5b729f9cbabd.png)

However, when I visit https://www.reddit.com/r/immigration/comments/t6kjez/can_you_apply_for_citizenship_earlier_than_the_90/ and I hover over that link in the second last comment, I see no change:
![image](https://user-images.githubusercontent.com/4270240/167998866-3c76a32f-c152-4bbb-88d5-f36a88980e30.png)

**Comment by igorlogius** [comment]
HI @peter-kehl, 

i did the following to reproduce the issue

1. installed the addon in a new fresh profile in a firefox 100.0 instance
2. installed the addon from  https://addons.mozilla.org/en-US/firefox/addon/indicate-if-link-is-bookmarked/
3. bookmarked the page  https://www.uscis.gov/citizenship-resource-center/learn-about-citizenship/naturalization-eligibility
4. open a new tab with https://www.reddit.com/r/immigration/comments/t6kjez/can_you_apply_for_citizenship_earlier_than_the_90/
5. scrolled down to the second last comment and moved the mouse over the link

But i was unable the reproduce the issue. (see Screenshots at the bottom of this post) 
Maybe some other addon is interfering?
Try disabeling some/all let me know if that changed anything.

Screenshots: 
![Logged in with Reddits Dark Theme enabled](https://i.imgur.com/19EKhvc.jpeg)
![Not Logged with default Light Theme](https://i.imgur.com/o4tT4yZ.jpeg)

**Comment by igorlogius** [comment]
I'll assume this issue has been resolved, if not, please let me know and i'll take another look.
